export const SELECT_CONTACT = 'SELECT_CONTACT'
export const CHANGE_CONTACT = 'CHANGE_CONTACT'
export const CLEAR_SELECTED_CONTACT = 'CLEAR_SELECTED_CONTACT'

export const FETCH_CONTACTS_PENDING = 'FETCH_CONTACTS_PENDING'
export const FETCH_CONTACTS_FULFILLED = 'FETCH_CONTACTS_FULFILLED'
export const FETCH_CONTACTS_FAILED = 'FETCH_CONTACTS_FAILED'

export const UPDATE_CONTACT_PENDING = 'UPDATE_CONTACT_PENDING'
export const UPDATE_CONTACT_FULFILLED = 'UPDATE_CONTACT_FULFILLED'
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED'

export const CREATE_CONTACT_PENDING = 'CREATE_CONTACT_PENDING'
export const CREATE_CONTACT_FULFILLED = 'CREATE_CONTACT_FULFILLED'
export const CREATE_CONTACT_FAILED = 'CREATE_CONTACT_FAILED'

export const DELETE_CONTACT_PENDING = 'DELETE_CONTACT_PENDING'
export const DELETE_CONTACT_FULFILLED = 'DELETE_CONTACT_FULFILLED'
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED'